import type { Metadata } from "next";
import Link from "next/link";

const SITE_URL = "https://latticeplugins.com";
const SLUG = "/blog/woocommerce-invoice-plugin-setup-checklist";

export const metadata: Metadata = {
  title: "WooCommerce Invoice Plugin Setup Checklist Before Launch",
  description:
    "A pre-purchase and setup checklist for WooCommerce stores choosing an invoice plugin: VAT fields, invoice numbers, PDFs, refunds, emails, downloads, and accountant export.",
  alternates: {
    canonical: `${SITE_URL}${SLUG}`,
  },
  openGraph: {
    title: "WooCommerce invoice plugin setup checklist",
    description:
      "Use this setup checklist before buying or enabling a WooCommerce invoice plugin for EU VAT/BTW orders, credit notes, PDFs, customer downloads, and accountant export.",
    url: `${SITE_URL}${SLUG}`,
    siteName: "Lattice Plugins",
    type: "article",
  },
};

const launchChecklist = [
  {
    phase: "Before checkout",
    checks: [
      "Company name, VAT/BTW number, invoice email, PO/reference, and billing country are collected before payment",
      "VAT validation rules are clear: optional, required for B2B, or validated against VIES when available",
      "Customers know whether the order will create a receipt, proforma, final VAT invoice, or credit note",
    ],
  },
  {
    phase: "When the order is paid",
    checks: [
      "Invoice number is created from a clean yearly sequence, not from abandoned checkout attempts",
      "Invoice date, paid date, VAT amount, tax rate, payment method, and customer VAT ID are stored on the order",
      "The PDF invoice is attached to the correct WooCommerce emails and can be regenerated by an admin",
    ],
  },
  {
    phase: "After purchase",
    checks: [
      "Customers can download their invoice from My Account without emailing support",
      "Refunds create a credit note with its own number and a reference to the original invoice",
      "Accountant export includes invoice number, order ID, VAT fields, PDF link, payment status, and credit-note relationship",
    ],
  },
];

const riskRows = [
  {
    risk: "Only testing a happy-path card payment",
    consequence: "Bank transfer, PayPal, Stripe refund, Klarna capture, or partial-payment orders can create invoice gaps later.",
    fix: "Run a setup test for each payment method before switching the plugin on for real orders.",
  },
  {
    risk: "Using order IDs as invoice numbers by default",
    consequence: "Failed and cancelled orders can make the invoice sequence harder to explain to an accountant.",
    fix: "Choose a separate invoice prefix and yearly sequence such as INV-2026-000148.",
  },
  {
    risk: "Collecting VAT details in order notes",
    consequence: "PDF templates, exports, customer downloads, and corrections become manual because the data is not structured.",
    fix: "Use dedicated checkout/order meta fields for VAT/BTW number, PO/reference, and invoice email.",
  },
  {
    risk: "Ignoring refunds until the first chargeback or return",
    consequence: "The store owner edits the original invoice or sends a manual negative PDF with no audit relationship.",
    fix: "Define credit-note numbering and original-invoice references before launch.",
  },
];

const setupTests = [
  "Place one B2C order and confirm the invoice PDF shows correct VAT totals.",
  "Place one B2B order with company/VAT details and confirm the data appears on the PDF and export.",
  "Refund a paid order and confirm a credit note is created instead of editing the original invoice.",
  "Open My Account as the customer and confirm the invoice download link works after logout/login.",
  "Send a test processing/completed order email and confirm the invoice attachment is present.",
  "Export one month of orders and check whether the accountant can match invoice numbers, VAT totals, payments, and refunds.",
];

const faq = [
  {
    q: "Should I complete this checklist before buying a WooCommerce invoice plugin?",
    a: "Yes. It prevents buying a PDF-only plugin when the real problem is VAT/BTW checkout data, refund credit notes, customer downloads, or accountant export.",
  },
  {
    q: "What is the most common setup mistake?",
    a: "Testing only a successful card payment. EU stores also need to test refunds, bank transfers, PayPal/Stripe edge cases, customer downloads, invoice email attachments, and month-end export.",
  },
  {
    q: "How does this relate to Lattice Invoices?",
    a: "Lattice Invoices is being positioned around this exact setup path: structured VAT fields, predictable invoice numbering, PDFs, credit notes, customer downloads, and accountant-ready order metadata.",
  },
  {
    q: "Can Lattice review my setup before early access?",
    a: "Yes. Use the early-access CTA with your store URL, country, current invoice plugin, payment methods, desired invoice number format, and refund requirements.",
  },
];

const mailto =
  "mailto:support@latticeplugins.com?subject=WooCommerce%20invoice%20setup%20checklist%20review&body=Hi%20Lattice%2C%0A%0AI%20want%20a%20WooCommerce%20invoice%20setup%20checklist%20review%20for%20Lattice%20Invoices%20early%20access.%0A%0AStore%20URL%3A%20%0ACountry%3A%20%0AB2B%20or%20B2C%3A%20%0ACurrent%20invoice%20plugin%3A%20%0APayment%20methods%3A%20%0AInvoice%20number%20format%3A%20%0ACredit%20notes%20needed%3A%20%0AAccountant%20export%20needed%3A%20";

const articleSchema = {
  "@context": "https://schema.org",
  "@type": "Article",
  headline: "WooCommerce invoice plugin setup checklist before launch",
  description:
    "A buyer-intent setup checklist for WooCommerce invoice plugins, VAT fields, invoice numbers, PDF delivery, refunds, customer downloads, and accountant export.",
  mainEntityOfPage: `${SITE_URL}${SLUG}`,
  publisher: {
    "@type": "Organization",
    name: "Lattice Plugins",
    url: SITE_URL,
  },
};

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faq.map((item) => ({
    "@type": "Question",
    name: item.q,
    acceptedAnswer: {
      "@type": "Answer",
      text: item.a,
    },
  })),
};

export default function WooCommerceInvoicePluginSetupChecklistPage() {
  return (
    <main className="min-h-screen bg-slate-50">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />

      <section className="bg-gradient-to-br from-slate-950 via-indigo-950 to-blue-900 text-white">
        <div className="max-w-5xl mx-auto px-6 py-16 lg:py-20">
          <p className="uppercase tracking-[0.3em] text-sm text-blue-200 mb-4">WooCommerce invoice setup</p>
          <h1 className="text-4xl md:text-6xl font-bold leading-tight mb-6">
            WooCommerce invoice plugin setup checklist before you launch.
          </h1>
          <p className="text-xl text-blue-50 leading-relaxed max-w-3xl mb-8">
            Do not enable an invoice plugin on live EU orders until checkout fields, invoice numbers, PDF emails, customer downloads, refunds, and accountant export have been tested. This checklist turns setup into a buying decision.
          </p>
          <div className="flex flex-col sm:flex-row gap-4">
            <a href={mailto} className="bg-green-500 text-white px-8 py-4 rounded-xl font-semibold hover:bg-green-400 transition shadow-lg text-center">
              Request setup review
            </a>
            <Link href="/woocommerce-eu-vat-invoices" className="bg-white/10 border border-white/20 text-white px-8 py-4 rounded-xl font-semibold hover:bg-white/15 transition text-center">
              View Lattice Invoices offer
            </Link>
          </div>
        </div>
      </section>

      <section className="max-w-6xl mx-auto px-6 py-14">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <article className="lg:col-span-2 space-y-8">
            <div className="bg-white rounded-2xl border shadow-sm p-8">
              <h2 className="text-3xl font-bold mb-4">Why setup matters more than the PDF template</h2>
              <p className="text-slate-700 leading-relaxed mb-4">
                Most WooCommerce invoice plugin comparisons focus on templates and email attachments. EU VAT stores need to go further: VAT/BTW fields must be captured before payment, invoice numbers must be predictable, refunds need credit notes, and customer downloads must keep support out of the inbox.
              </p>
              <p className="text-slate-700 leading-relaxed">
                Use this checklist before buying, migrating, or enabling an invoice plugin. If several items are missing, the store likely needs a workflow-first invoice plugin rather than another styling add-on.
              </p>
            </div>

            <div className="space-y-5">
              {launchChecklist.map((section) => (
                <div key={section.phase} className="bg-white rounded-2xl border shadow-sm p-8">
                  <h2 className="text-2xl font-bold mb-5">{section.phase}</h2>
                  <div className="space-y-3">
                    {section.checks.map((check) => (
                      <div key={check} className="flex gap-3 rounded-xl bg-blue-50 border border-blue-100 p-4">
                        <span className="text-blue-700 font-bold">✓</span>
                        <span className="text-slate-800">{check}</span>
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>

            <div className="bg-white rounded-2xl border shadow-sm p-8 overflow-hidden">
              <h2 className="text-3xl font-bold mb-6">Setup risks that cause invoice cleanup later</h2>
              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                  <thead>
                    <tr className="bg-slate-100 text-slate-700">
                      <th className="p-4 rounded-l-xl">Risk</th>
                      <th className="p-4">What happens later</th>
                      <th className="p-4 rounded-r-xl">Fix before launch</th>
                    </tr>
                  </thead>
                  <tbody>
                    {riskRows.map((row) => (
                      <tr key={row.risk} className="border-b border-slate-100 align-top">
                        <td className="p-4 font-semibold text-slate-900">{row.risk}</td>
                        <td className="p-4 text-slate-600">{row.consequence}</td>
                        <td className="p-4 text-slate-800">{row.fix}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            <div className="bg-green-50 border border-green-100 rounded-2xl p-8">
              <h2 className="text-3xl font-bold mb-5">Six setup tests to run before real orders</h2>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {setupTests.map((test, index) => (
                  <div key={test} className="flex gap-3 bg-white rounded-xl border border-green-100 p-4">
                    <span className="text-green-700 font-bold">{index + 1}</span>
                    <span className="text-slate-800">{test}</span>
                  </div>
                ))}
              </div>
            </div>

            <div className="bg-white rounded-2xl border shadow-sm p-8">
              <h2 className="text-3xl font-bold mb-6">FAQ</h2>
              <div className="space-y-5">
                {faq.map((item) => (
                  <div key={item.q}>
                    <h3 className="text-xl font-bold mb-2">{item.q}</h3>
                    <p className="text-slate-700 leading-relaxed">{item.a}</p>
                  </div>
                ))}
              </div>
            </div>
          </article>

          <aside className="space-y-6">
            <div className="bg-white rounded-2xl border shadow-sm p-6 sticky top-6">
              <p className="text-sm uppercase tracking-[0.25em] text-blue-600 font-semibold mb-2">Pre-purchase review</p>
              <h2 className="text-2xl font-bold mb-3">Turn this checklist into the €49 early-access path</h2>
              <p className="text-slate-700 leading-relaxed mb-5">
                Send the store details once. The reply can qualify whether Lattice Invoices is a fit before the public paid listing is finalized.
              </p>
              <a href={mailto} className="block text-center bg-blue-600 text-white px-6 py-3 rounded-xl font-semibold hover:bg-blue-700 transition mb-3">
                Request setup review
              </a>
              <Link href="/woocommerce-eu-vat-invoices" className="block text-center border border-slate-200 px-6 py-3 rounded-xl font-semibold hover:border-blue-400 transition mb-3">
                View Lattice Invoices
              </Link>
              <Link href="/docs/woocommerce-eu-vat-invoice-setup" className="block text-center border border-slate-200 px-6 py-3 rounded-xl font-semibold hover:border-blue-400 transition mb-3">
                Read full setup docs
              </Link>
              <Link href="/blog/woocommerce-invoice-plugin-cost" className="block text-center border border-slate-200 px-6 py-3 rounded-xl font-semibold hover:border-blue-400 transition">
                Compare plugin cost
              </Link>
            </div>
          </aside>
        </div>
      </section>
    </main>
  );
}
